import{Component,signal}from'@angular/core';
import{FormsModule}from'@angular/forms';
import{LucideBellRing,LucideMail,LucideSave,LucideShieldCheck}from'@lucide/angular';
import{ApiService}from'../../core/api.service';
import{SystemSettings}from'../../core/models';

@Component({standalone:true,imports:[FormsModule,LucideBellRing,LucideMail,LucideSave,LucideShieldCheck],template:`
<header><h1>Cài đặt hệ thống</h1><p>Quản lý email nhận thông báo vận hành cửa hàng</p></header><main><form class="panel" (ngSubmit)="save()"><div class="section-title"><span><svg lucideBellRing></svg></span><div><h2>Thông báo đơn hàng</h2><p>Các địa chỉ dưới đây sẽ nhận email khi có đơn hàng mới.</p></div></div><label><span>Email quản lý<small>Nhận thông tin tổng quan và thông báo đơn mới</small></span><div><svg lucideMail></svg><input class="field" type="email" name="managerEmail" [(ngModel)]="form.managerEmail" required></div></label><label><span>Email kế toán<small>Nhận thông tin thanh toán và giá trị đơn hàng</small></span><div><svg lucideMail></svg><input class="field" type="email" name="accountantEmail" [(ngModel)]="form.accountantEmail" required></div></label><div class="security"><svg lucideShieldCheck></svg><p><b>Dữ liệu được bảo vệ</b><small>Chỉ tài khoản Administrator mới có quyền xem và thay đổi thiết lập này.</small></p></div>@if(message()){<div class="notice" [class.error]="error()">{{message()}}</div>}<footer><button class="btn btn-primary" [disabled]="saving()"><svg lucideSave></svg>{{saving()?'Đang lưu...':'Lưu thay đổi'}}</button></footer></form></main>
`,styles:[`header{padding:26px 32px;background:#fff;border-bottom:1px solid var(--line)}header h1{margin:0;font-size:24px}header p{color:var(--muted);margin:5px 0 0}main{padding:32px;max-width:900px}form{padding:26px}.section-title{display:flex;gap:14px;align-items:center;border-bottom:1px solid var(--line);padding-bottom:22px}.section-title>span{width:44px;height:44px;background:#e8eeff;color:var(--blue);border-radius:8px;display:grid;place-items:center}.section-title svg{width:22px}.section-title h2{font-size:18px;margin:0}.section-title p{color:var(--muted);margin:5px 0 0}.panel>label{display:grid;grid-template-columns:1fr 1.25fr;gap:30px;align-items:center;padding:22px 0;border-bottom:1px solid var(--line)}label>span{font-weight:700;display:flex;flex-direction:column;gap:5px}label small{font-weight:400;color:var(--muted)}label>div{position:relative}label>div svg{position:absolute;left:12px;top:11px;width:18px;color:var(--muted)}label input{width:100%;padding-left:40px}.security{display:flex;gap:12px;background:#ecfdf5;color:var(--success);padding:14px;margin-top:22px;border-radius:8px}.security svg{width:22px;flex:none}.security p{margin:0;display:flex;flex-direction:column;gap:4px}.security small{color:#39745a}.notice{margin-top:18px;padding:11px;background:#ecfdf5;color:var(--success);border-radius:6px}.notice.error{background:#fef2f2;color:var(--red)}footer{display:flex;justify-content:flex-end;margin-top:22px}footer svg{width:17px}@media(max-width:700px){header,main{padding:18px}form{padding:18px}.panel>label{grid-template-columns:1fr;gap:10px}}`]})
export class AdminSettingsPage{form:SystemSettings={managerEmail:'',accountantEmail:''};saving=signal(false);message=signal('');error=signal(false);constructor(private api:ApiService){api.settings().subscribe({next:x=>this.form=x,error:()=>{this.error.set(true);this.message.set('Không thể tải cài đặt hệ thống.')}})}save(){this.saving.set(true);this.message.set('');this.api.updateSettings(this.form).subscribe({next:()=>{this.error.set(false);this.message.set('Đã lưu cài đặt thành công.');this.saving.set(false)},error:()=>{this.error.set(true);this.message.set('Không thể lưu cài đặt.');this.saving.set(false)}})}}
